cache:
  directories:
    - $HOME/.composer/cache/files
    - $HOME/.php-cs-fixer

env:
  global:
    - SETUP=basic

git:
  depth: 2

language: php

matrix:
  allow_failures:
    - php: 7.3
#    - php: nightly
  fast_finish: true
  include:
    - php: 7.1
    - php: 7.2
    - php: 7.3
#    - php: nightly
#    - os: osx
#      osx_image: xcode7.2

sudo: false

#before_install:
#  - cp .env.travis .env
#  - mysql -e 'create database homestead;'
#  - composer self-update
#  - composer install --prefer-source --no-interaction --dev
#  - php artisan migrate
#  - php artisan db:seed

install:
  - if [[ $SETUP = 'basic' ]]; then travis_retry composer install --no-interaction --prefer-dist; fi
  - if [[ $SETUP = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-stable; fi
  - if [[ $SETUP = 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-lowest --prefer-stable; fi

#before_script:
#  - php artisan key:generate

script:
  #- sh ./resources/bin/travis--require-branch-pull-request.sh
  - composer ci

#before_cache:
#  -

#after_success:
#  -

#after_failure:
#  -

#before_deploy:
#  -

#deploy:
#  -

#after_deploy:
#  -

#after_script:
#  -
